# Generated by Django 4.0.3 on 2022-05-18 06:12
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("form_designer", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="formfield",
            old_name="name",
            new_name="_old_name",
        ),
        migrations.AlterField(
            model_name="formfield",
            name="_old_name",
            field=models.CharField(editable=False, max_length=100, null=True),
        ),
        migrations.AlterUniqueTogether(
            name="formfield",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="formfield",
            name="name",
            field=models.CharField(
                default="",
                help_text="Data is saved using this name. Changing it may result in data loss. This field only allows a-z, 0-9, - and _ as characters.",
                max_length=100,
                validators=[
                    django.core.validators.RegexValidator(
                        "^[-a-z0-9_]+$",
                        message="Enter a value consisting only of lowercase letters, numbers, dashes and the underscore.",
                    )
                ],
                verbose_name="field name",
            ),
            preserve_default=False,
        ),
    ]
