# Generated by Django 4.1.1 on 2022-10-02 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("form_designer", "0004_alter_formsubmission_options_and_more"),
    ]

    operations = [
        migrations.RenameField("form", "config_json", "config"),
        migrations.AlterField(
            model_name="form",
            name="config",
            field=models.JSONField(blank=True, verbose_name="config"),
        ),
        migrations.AlterField(
            model_name="formsubmission",
            name="data",
            field=models.JSONField(verbose_name="data"),
        ),
    ]
